version: "3"

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./../index.html:/usr/share/nginx/html/index.html:ro
      - ./../js:/usr/share/nginx/html/js:ro
      - ./../css:/usr/share/nginx/html/css:ro
    ports:
      - 8080:80